# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, python3Packages, rclpy }:
buildRosPackage rec {
  pname = "ros-humble-antenna-pkg";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  buildInputs = [ python3Packages.black ];
  propagatedBuildInputs = [ python3Packages.pyserial rclpy ];

  meta = {
    description = "Tracking antenna ROS node";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
